package com.finflow.moneytracker.ui.budget

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.finflow.moneytracker.data.local.entity.Budget
import com.finflow.moneytracker.data.local.entity.BudgetAllocation
import com.finflow.moneytracker.data.local.entity.BudgetCycleType
import com.finflow.moneytracker.data.local.entity.Category
import com.finflow.moneytracker.data.local.entity.Transaction
import com.finflow.moneytracker.data.local.entity.Wallet
import com.finflow.moneytracker.data.repository.BudgetRepository
import com.finflow.moneytracker.data.repository.CategoryRepository
import com.finflow.moneytracker.data.repository.TransactionRepository
import com.finflow.moneytracker.data.repository.WalletRepository
import com.finflow.moneytracker.data.local.model.CategoryType
import java.text.NumberFormat
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Locale
import kotlin.math.abs
import kotlin.math.ceil
import kotlin.math.roundToLong
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.flatMapLatest
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch

enum class BudgetProgressState {
    SAFE,
    WARNING,
    DANGER
}

data class BudgetCategoryProgressUi(
    val categoryId: Long,
    val categoryName: String,
    val allocated: Long,
    val spent: Long,
    val remaining: Long,
    val usagePercent: Int,
    val progressState: BudgetProgressState
)

data class BudgetUiState(
    val isLoading: Boolean = true,
    val isEmpty: Boolean = false,
    val periodLabel: String = "",
    val budgetName: String = "",
    val walletName: String = "",
    val walletScopeLabel: String = "",
    val plannedBudget: Long = 0L,
    val totalBudget: Long = 0L,
    val spent: Long = 0L,
    val remaining: Long = 0L,
    val usagePercent: Int = 0,
    val isAutoGenerated: Boolean = true,
    val isManualOverride: Boolean = false,
    val canCreateManually: Boolean = false,
    val canEditManually: Boolean = false,
    val progressState: BudgetProgressState = BudgetProgressState.SAFE,
    val alertMessage: String? = null,
    val comparisonMessage: String? = null,
    val burnRateForecastMessage: String? = null,
    val categoryProgress: List<BudgetCategoryProgressUi> = emptyList()
)

@OptIn(ExperimentalCoroutinesApi::class)
class BudgetViewModel(
    private val budgetRepository: BudgetRepository,
    private val walletRepository: WalletRepository,
    private val categoryRepository: CategoryRepository,
    private val transactionRepository: TransactionRepository
) : ViewModel() {

    private data class CombinedStaticData(
        val wallets: List<com.finflow.moneytracker.data.local.entity.Wallet>,
        val categories: List<Category>,
        val transactions: List<Transaction>
    )

    companion object {
        private val TYPE_EXPENSE = CategoryType.EXPENSE
        private const val DEFAULT_LOCAL_USER = "local_user"
        private const val DEFAULT_WALLET_NAME = "Ví mặc định"
        private const val DAY_MILLIS = 24L * 60L * 60L * 1000L
    }

    private val currentDateFlow = MutableStateFlow(System.currentTimeMillis())

    private val budgetFlow = currentDateFlow.flatMapLatest { date ->
        budgetRepository.getBudgetForDateStream(BudgetCycleType.MONTHLY, date)
    }

    private val combinedStaticDataFlow = combine(
        walletRepository.getWalletsStream(),
        categoryRepository.getAllCategoriesStream(),
        transactionRepository.getAllTransactionsStream()
    ) { wallets, categories, transactions ->
        CombinedStaticData(
            wallets = wallets,
            categories = categories,
            transactions = transactions
        )
    }

    val uiState: StateFlow<BudgetUiState> = combine(
        budgetFlow,
        combinedStaticDataFlow
    ) { budget, staticData ->

        val wallets = staticData.wallets
        val categories = staticData.categories
        val transactions = staticData.transactions

        if (budget == null) {
            return@combine BudgetUiState(
                isLoading = false,
                isEmpty = true,
                periodLabel = formatPeriodLabel(currentDateFlow.value),
                canCreateManually = true
            )
        }

        val expenseCategories = categories.filter { it.type == TYPE_EXPENSE }
        val categoryLimitById = expenseCategories.associate { category ->
            category.id to (category.monthlyBudgetLimit ?: 0L)
        }
        val categoryTotalBudget = categoryLimitById.values.sum()
        val expenseCategoryIds = expenseCategories.map { it.id }.toSet()

        val expenseTransactions = transactions.filter { tx ->
            tx.date in budget.periodStart..budget.periodEnd &&
                tx.categoryId in expenseCategoryIds &&
                tx.amount < 0 &&
                (budget.walletId == null || tx.walletId == budget.walletId)
        }

        val totalSpent = expenseTransactions.sumOf { abs(it.amount) }
        val totalBudget = categoryTotalBudget
        val totalRemaining = totalBudget - totalSpent
        val usagePercent = percentage(totalSpent, totalBudget)
        val walletName = wallets.firstOrNull { it.id == budget.walletId }?.name ?: "Tất cả ví"
        val walletScopeLabel = if (budget.walletId == null) {
            "Phạm vi ví: Tất cả ví"
        } else {
            "Phạm vi ví: $walletName"
        }

        val spentByCategory = expenseTransactions
            .groupBy { it.categoryId }
            .mapValues { (_, txs) -> txs.sumOf { abs(it.amount) } }

        val categoryProgress = expenseCategories.map { category ->
            val allocatedAmount = categoryLimitById[category.id] ?: 0L
            val categorySpent = spentByCategory[category.id] ?: 0L
            val categoryRemaining = allocatedAmount - categorySpent
            val categoryUsage = percentage(categorySpent, allocatedAmount)

            BudgetCategoryProgressUi(
                categoryId = category.id,
                categoryName = category.name,
                allocated = allocatedAmount,
                spent = categorySpent,
                remaining = categoryRemaining,
                usagePercent = categoryUsage,
                progressState = mapUsageToState(categoryUsage)
            )
        }.sortedByDescending { it.spent }

        val (previousStart, previousEnd) = getPreviousMonthRange(budget.periodStart)
        val previousExpenseTransactions = transactions.filter { tx ->
            tx.date in previousStart..previousEnd &&
                tx.categoryId in expenseCategoryIds &&
                tx.amount < 0 &&
                (budget.walletId == null || tx.walletId == budget.walletId)
        }
        val comparisonMessage = if (previousExpenseTransactions.isEmpty()) {
            null
        } else {
            val previousSpent = previousExpenseTransactions.sumOf { abs(it.amount) }
            val delta = totalSpent - previousSpent
            if (delta == 0L) {
                "Chi tiêu giữ nguyên so với kỳ trước"
            } else {
                val trend = if (delta > 0) "tăng" else "giảm"
                "Chi tiêu $trend ${formatCurrency(abs(delta))} so với kỳ trước"
            }
        }
        val burnRateForecastMessage = buildBurnRateForecastMessage(
            periodStart = budget.periodStart,
            periodEnd = budget.periodEnd,
            totalSpent = totalSpent,
            totalBudget = totalBudget
        )

        BudgetUiState(
            isLoading = false,
            isEmpty = false,
            periodLabel = formatPeriodLabel(budget.periodStart),
            budgetName = budget.name,
            walletName = walletName,
            walletScopeLabel = walletScopeLabel,
            plannedBudget = categoryTotalBudget,
            totalBudget = totalBudget,
            spent = totalSpent,
            remaining = totalRemaining,
            usagePercent = usagePercent,
            isAutoGenerated = true,
            isManualOverride = false,
            canCreateManually = false,
            canEditManually = false,
            progressState = mapUsageToState(usagePercent),
            alertMessage = buildAlertMessage(totalSpent, totalBudget),
            comparisonMessage = comparisonMessage,
            burnRateForecastMessage = burnRateForecastMessage,
            categoryProgress = categoryProgress
        )
    }.stateIn(
        scope = viewModelScope,
        started = SharingStarted.WhileSubscribed(5_000L),
        initialValue = BudgetUiState()
    )

    init {
        viewModelScope.launch {
            ensureCurrentMonthlyBudget()
            syncCurrentBudgetWithCategoryLimits()
        }
    }

    fun refreshCurrentPeriod() {
        viewModelScope.launch {
            syncCurrentBudgetWithCategoryLimits()
            currentDateFlow.value = System.currentTimeMillis()
        }
    }

    fun updateCategoryBudgetLimit(categoryId: Long, monthlyBudgetLimit: Long) {
        if (monthlyBudgetLimit < 0L) {
            return
        }

        viewModelScope.launch {
            val categories = categoryRepository.getAllCategoriesStream().first()
            val targetCategory = categories.firstOrNull {
                it.id == categoryId && it.type == TYPE_EXPENSE
            } ?: return@launch

            categoryRepository.updateCategory(
                targetCategory.copy(monthlyBudgetLimit = monthlyBudgetLimit)
            )
            syncCurrentBudgetWithCategoryLimits()
        }
    }

    fun editCurrentBudget(newPlannedAmount: Long) {
        if (newPlannedAmount < 0L) {
            return
        }

        viewModelScope.launch {
            val now = System.currentTimeMillis()
            val currentBudget = budgetRepository
                .getBudgetForDateStream(BudgetCycleType.MONTHLY, now)
                .first()
                ?: return@launch

            val currentAllocations = budgetRepository
                .getAllocationsByBudgetStream(currentBudget.id)
                .first()

            val totalAllocated = currentAllocations.sumOf { it.allocatedAmount }
            val rebalancedAllocations = if (currentAllocations.isEmpty() || totalAllocated <= 0L) {
                currentAllocations
            } else {
                var remaining = newPlannedAmount
                currentAllocations.mapIndexed { index, allocation ->
                    val isLast = index == currentAllocations.lastIndex
                    val amount = if (isLast) {
                        remaining
                    } else {
                        val ratio = allocation.allocatedAmount.toDouble() / totalAllocated.toDouble()
                        val value = (newPlannedAmount * ratio).roundToLong().coerceAtLeast(0L)
                        remaining -= value
                        value
                    }
                    allocation.copy(allocatedAmount = amount)
                }
            }

            budgetRepository.updateBudget(
                currentBudget.copy(
                    plannedAmount = newPlannedAmount,
                    isAutoGenerated = false,
                    manualOverride = true
                )
            )

            if (rebalancedAllocations.isNotEmpty()) {
                budgetRepository.upsertAllocations(currentBudget.id, rebalancedAllocations)
            }
        }
    }

    private suspend fun ensureCurrentMonthlyBudget() {
        val now = System.currentTimeMillis()
        val budget = budgetRepository
            .getBudgetForDateStream(BudgetCycleType.MONTHLY, now)
            .first()
        if (budget != null) {
            return
        }

        val categories = categoryRepository.getAllCategoriesStream().first()
        val expenseCategories = categories.filter { it.type == TYPE_EXPENSE }

        val defaultWallet = getOrCreateDefaultWallet()
        val (periodStart, periodEnd) = getMonthRange(now)

        val plannedAmount = expenseCategories.sumOf { it.monthlyBudgetLimit ?: 0L }

        val newBudget = Budget(
            userId = defaultWallet.userId,
            walletId = null,
            name = "Ngân sách tháng",
            cycleType = BudgetCycleType.MONTHLY,
            periodStart = periodStart,
            periodEnd = periodEnd,
            plannedAmount = plannedAmount,
            carryOverAmount = 0L,
            autoResetEnabled = true,
            carryOverEnabled = true,
            isAutoGenerated = true,
            manualOverride = false
        )
        budgetRepository.insertBudget(newBudget)

        budgetRepository.upsertAllocations(
            newBudget.id,
            buildCategoryLimitAllocations(newBudget.id, expenseCategories)
        )
    }

    private suspend fun syncCurrentBudgetWithCategoryLimits() {
        val now = System.currentTimeMillis()
        val existingBudget = budgetRepository
            .getBudgetForDateStream(BudgetCycleType.MONTHLY, now)
            .first()

        val categories = categoryRepository.getAllCategoriesStream().first()
        val expenseCategories = categories.filter { it.type == TYPE_EXPENSE }
        val totalCategoryLimit = expenseCategories.sumOf { it.monthlyBudgetLimit ?: 0L }

        if (existingBudget == null) {
            val defaultWallet = getOrCreateDefaultWallet()
            val (periodStart, periodEnd) = getMonthRange(now)

            val autoBudget = Budget(
                userId = defaultWallet.userId,
                walletId = null,
                name = "Ngân sách tháng",
                cycleType = BudgetCycleType.MONTHLY,
                periodStart = periodStart,
                periodEnd = periodEnd,
                plannedAmount = totalCategoryLimit,
                carryOverAmount = 0L,
                autoResetEnabled = true,
                carryOverEnabled = true,
                isAutoGenerated = true,
                manualOverride = false
            )
            budgetRepository.insertBudget(autoBudget)
            budgetRepository.upsertAllocations(
                autoBudget.id,
                buildCategoryLimitAllocations(autoBudget.id, expenseCategories)
            )
            return
        }

        val needsScopeUpdate =
            existingBudget.walletId != null &&
                existingBudget.isAutoGenerated &&
                existingBudget.manualOverride.not()

        val needsBudgetUpdate =
            existingBudget.plannedAmount != totalCategoryLimit ||
                existingBudget.isAutoGenerated.not() ||
                existingBudget.manualOverride ||
                needsScopeUpdate

        if (needsBudgetUpdate) {
            budgetRepository.updateBudget(
                existingBudget.copy(
                    plannedAmount = totalCategoryLimit,
                    isAutoGenerated = true,
                    manualOverride = false,
                    walletId = if (needsScopeUpdate) null else existingBudget.walletId
                )
            )
        }

        val desiredAllocations = buildCategoryLimitAllocations(existingBudget.id, expenseCategories)
        val currentAllocations = budgetRepository
            .getAllocationsByBudgetStream(existingBudget.id)
            .first()
            .associate { allocation -> allocation.categoryId to allocation.allocatedAmount }
        val desiredAllocationMap = desiredAllocations.associate { allocation ->
            allocation.categoryId to allocation.allocatedAmount
        }

        if (currentAllocations != desiredAllocationMap) {
            budgetRepository.upsertAllocations(existingBudget.id, desiredAllocations)
        }
    }

    private suspend fun getOrCreateDefaultWallet(): Wallet {
        val existingWallet = walletRepository.getWalletsStream().first().firstOrNull()
        if (existingWallet != null) {
            return existingWallet
        }

        val createdWallet = Wallet(
            userId = DEFAULT_LOCAL_USER,
            name = DEFAULT_WALLET_NAME,
            balance = 0L
        )
        walletRepository.insertWallet(createdWallet)
        return walletRepository.getWalletsStream()
            .first()
            .firstOrNull { it.name == DEFAULT_WALLET_NAME }
            ?: walletRepository.getWalletsStream().first().first()
    }

    private fun buildCategoryLimitAllocations(
        budgetId: String,
        expenseCategories: List<Category>
    ): List<BudgetAllocation> {
        return expenseCategories.map { category ->
            BudgetAllocation(
                budgetId = budgetId,
                categoryId = category.id,
                allocatedAmount = (category.monthlyBudgetLimit ?: 0L).coerceAtLeast(0L)
            )
        }
    }

    private fun getPreviousMonthRange(currentPeriodStart: Long): Pair<Long, Long> {
        val previousMonthTimestamp = Calendar.getInstance().run {
            timeInMillis = currentPeriodStart
            add(Calendar.MONTH, -1)
            timeInMillis
        }
        return getMonthRange(previousMonthTimestamp)
    }

    private fun getMonthRange(timestamp: Long): Pair<Long, Long> {
        val calendar = Calendar.getInstance().apply {
            timeInMillis = timestamp
            set(Calendar.DAY_OF_MONTH, 1)
            set(Calendar.HOUR_OF_DAY, 0)
            set(Calendar.MINUTE, 0)
            set(Calendar.SECOND, 0)
            set(Calendar.MILLISECOND, 0)
        }

        val start = calendar.timeInMillis
        calendar.add(Calendar.MONTH, 1)
        calendar.add(Calendar.MILLISECOND, -1)
        val end = calendar.timeInMillis

        return start to end
    }

    private fun percentage(value: Long, total: Long): Int {
        if (total <= 0L) {
            return 0
        }
        return ((value * 100f) / total).toInt().coerceAtLeast(0)
    }

    private fun mapUsageToState(usagePercent: Int): BudgetProgressState {
        return when {
            usagePercent > 100 -> BudgetProgressState.DANGER
            usagePercent >= 80 -> BudgetProgressState.WARNING
            else -> BudgetProgressState.SAFE
        }
    }

    private fun buildAlertMessage(totalSpent: Long, totalBudget: Long): String? {
        if (totalBudget <= 0L) {
            return if (totalSpent > 0L) {
                "Bạn đang chi tiêu nhưng chưa đặt ngân sách danh mục"
            } else {
                null
            }
        }

        val usagePercent = percentage(totalSpent, totalBudget)
        return when {
            totalSpent > totalBudget -> {
                val overAmount = totalSpent - totalBudget
                "Bạn đã vượt ${formatCurrency(overAmount)} so với ngân sách tháng"
            }
            totalSpent == totalBudget -> "Bạn đã chạm ngưỡng 100% ngân sách tháng"
            usagePercent >= 80 -> "Bạn đã dùng hơn 80% ngân sách tháng"
            else -> null
        }
    }

    private fun buildBurnRateForecastMessage(
        periodStart: Long,
        periodEnd: Long,
        totalSpent: Long,
        totalBudget: Long
    ): String? {
        if (totalBudget <= 0L) {
            return null
        }
        if (totalSpent <= 0L) {
            return "Chưa đủ dữ liệu chi tiêu để dự báo chạm trần"
        }

        val now = System.currentTimeMillis().coerceIn(periodStart, periodEnd)
        val elapsedDays = (((now - periodStart) / DAY_MILLIS) + 1L).coerceAtLeast(1L)
        val dailyBurnRate = totalSpent.toDouble() / elapsedDays.toDouble()
        if (dailyBurnRate <= 0.0) {
            return null
        }

        val remaining = (totalBudget - totalSpent).coerceAtLeast(0L)
        if (remaining == 0L) {
            return "Bạn đã chạm trần ngân sách ở kỳ hiện tại"
        }

        val daysToHitCap = ceil(remaining.toDouble() / dailyBurnRate).toLong().coerceAtLeast(1L)
        val projectedHitDate = now + (daysToHitCap * DAY_MILLIS)

        return if (projectedHitDate <= periodEnd) {
            "Với tốc độ hiện tại, có thể chạm trần sau $daysToHitCap ngày (${formatShortDate(projectedHitDate)})"
        } else {
            "Với tốc độ hiện tại, có thể chưa chạm trần trong kỳ này"
        }
    }

    private fun formatPeriodLabel(dateMillis: Long): String {
        return SimpleDateFormat("MM/yyyy", Locale("vi", "VN")).format(dateMillis)
    }

    private fun formatCurrency(value: Long): String {
        val formatter = NumberFormat.getCurrencyInstance(Locale("vi", "VN"))
        return formatter.format(value).replace("₫", "").trim() + " ₫"
    }

    private fun formatShortDate(dateMillis: Long): String {
        return SimpleDateFormat("dd/MM", Locale("vi", "VN")).format(dateMillis)
    }
}
