package com.finflow.moneytracker.ui.budget

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.finflow.moneytracker.data.local.entity.Budget
import com.finflow.moneytracker.data.local.entity.BudgetAllocation
import com.finflow.moneytracker.data.local.entity.BudgetCycleType
import com.finflow.moneytracker.data.local.entity.Category
import com.finflow.moneytracker.data.local.entity.Transaction
import com.finflow.moneytracker.data.local.entity.Wallet
import com.finflow.moneytracker.data.repository.BudgetRepository
import com.finflow.moneytracker.data.repository.CategoryRepository
import com.finflow.moneytracker.data.repository.TransactionRepository
import com.finflow.moneytracker.data.repository.WalletRepository
import java.text.NumberFormat
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Locale
import kotlin.math.abs
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.flatMapLatest
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch

enum class BudgetProgressState {
    SAFE,
    WARNING,
    DANGER
}

data class BudgetCategoryProgressUi(
    val categoryId: String,
    val categoryName: String,
    val allocated: Long,
    val spent: Long,
    val remaining: Long,
    val usagePercent: Int,
    val progressState: BudgetProgressState
)

data class BudgetUiState(
    val isLoading: Boolean = true,
    val isEmpty: Boolean = false,
    val periodLabel: String = "",
    val budgetName: String = "",
    val walletName: String = "",
    val plannedBudget: Long = 0L,
    val totalBudget: Long = 0L,
    val spent: Long = 0L,
    val remaining: Long = 0L,
    val usagePercent: Int = 0,
    val isAutoGenerated: Boolean = true,
    val isManualOverride: Boolean = false,
    val canCreateManually: Boolean = false,
    val canEditManually: Boolean = false,
    val progressState: BudgetProgressState = BudgetProgressState.SAFE,
    val alertMessage: String? = null,
    val comparisonMessage: String? = null,
    val categoryProgress: List<BudgetCategoryProgressUi> = emptyList()
)

@OptIn(ExperimentalCoroutinesApi::class)
class BudgetViewModel(
    private val budgetRepository: BudgetRepository,
    private val walletRepository: WalletRepository,
    private val categoryRepository: CategoryRepository,
    private val transactionRepository: TransactionRepository
) : ViewModel() {

    private data class CombinedStaticData(
        val wallets: List<com.finflow.moneytracker.data.local.entity.Wallet>,
        val categories: List<Category>,
        val transactions: List<Transaction>
    )

    companion object {
        private const val TYPE_EXPENSE = 0
        private const val DEFAULT_PLANNED_BUDGET = 5_000_000L
        private const val DEFAULT_LOCAL_USER = "local_user"
        private const val DEFAULT_WALLET_NAME = "Ví mặc định"
    }

    private val currentDateFlow = MutableStateFlow(System.currentTimeMillis())

    private val budgetFlow = currentDateFlow.flatMapLatest { date ->
        budgetRepository.getBudgetForDateStream(BudgetCycleType.MONTHLY, date)
    }

    private val allocationFlow = budgetFlow.flatMapLatest { budget ->
        if (budget == null) {
            flowOf(emptyList())
        } else {
            budgetRepository.getAllocationsByBudgetStream(budget.id)
        }
    }

    private val combinedStaticDataFlow = combine(
        walletRepository.getWalletsStream(),
        categoryRepository.getAllCategoriesStream(),
        transactionRepository.getAllTransactionsStream()
    ) { wallets, categories, transactions ->
        CombinedStaticData(
            wallets = wallets,
            categories = categories,
            transactions = transactions
        )
    }

    val uiState: StateFlow<BudgetUiState> = combine(
        budgetFlow,
        allocationFlow,
        combinedStaticDataFlow
    ) { budget, allocations, staticData ->

        val wallets = staticData.wallets
        val categories = staticData.categories
        val transactions = staticData.transactions

        if (budget == null) {
            return@combine BudgetUiState(
                isLoading = false,
                isEmpty = true,
                periodLabel = formatPeriodLabel(currentDateFlow.value),
                canCreateManually = true
            )
        }

        val expenseCategories = categories.filter { it.type == TYPE_EXPENSE }
        val expenseCategoryIds = expenseCategories.map { it.id }.toSet()

        val expenseTransactions = transactions.filter { tx ->
            tx.date in budget.periodStart..budget.periodEnd &&
                tx.categoryId in expenseCategoryIds &&
                tx.amount < 0 &&
                (budget.walletId == null || tx.walletId == budget.walletId)
        }

        val totalSpent = expenseTransactions.sumOf { abs(it.amount) }
        val totalBudget = budget.plannedAmount + budget.carryOverAmount
        val totalRemaining = totalBudget - totalSpent
        val usagePercent = percentage(totalSpent, totalBudget)

        val allocationByCategory = allocations.associateBy { it.categoryId }
        val spentByCategory = expenseTransactions
            .groupBy { it.categoryId }
            .mapValues { (_, txs) -> txs.sumOf { abs(it.amount) } }

        val categoryProgress = expenseCategories.map { category ->
            val allocatedAmount = allocationByCategory[category.id]?.allocatedAmount
                ?: category.monthlyBudgetLimit
                ?: 0L
            val categorySpent = spentByCategory[category.id] ?: 0L
            val categoryRemaining = allocatedAmount - categorySpent
            val categoryUsage = percentage(categorySpent, allocatedAmount)

            BudgetCategoryProgressUi(
                categoryId = category.id,
                categoryName = category.name,
                allocated = allocatedAmount,
                spent = categorySpent,
                remaining = categoryRemaining,
                usagePercent = categoryUsage,
                progressState = mapUsageToState(categoryUsage)
            )
        }.sortedByDescending { it.spent }

        val (previousStart, previousEnd) = getPreviousMonthRange(budget.periodStart)
        val previousExpenseTransactions = transactions.filter { tx ->
            tx.date in previousStart..previousEnd &&
                tx.categoryId in expenseCategoryIds &&
                tx.amount < 0 &&
                (budget.walletId == null || tx.walletId == budget.walletId)
        }
        val comparisonMessage = if (previousExpenseTransactions.isEmpty()) {
            null
        } else {
            val previousSpent = previousExpenseTransactions.sumOf { abs(it.amount) }
            val delta = totalSpent - previousSpent
            if (delta == 0L) {
                "Chi tiêu giữ nguyên so với kỳ trước"
            } else {
                val trend = if (delta > 0) "tăng" else "giảm"
                "Chi tiêu $trend ${formatCurrency(abs(delta))} so với kỳ trước"
            }
        }

        BudgetUiState(
            isLoading = false,
            isEmpty = false,
            periodLabel = formatPeriodLabel(budget.periodStart),
            budgetName = budget.name,
            walletName = wallets.firstOrNull { it.id == budget.walletId }?.name ?: "Tất cả ví",
            plannedBudget = budget.plannedAmount,
            totalBudget = totalBudget,
            spent = totalSpent,
            remaining = totalRemaining,
            usagePercent = usagePercent,
            isAutoGenerated = budget.isAutoGenerated,
            isManualOverride = budget.manualOverride,
            canCreateManually = false,
            canEditManually = true,
            progressState = mapUsageToState(usagePercent),
            alertMessage = buildAlertMessage(usagePercent),
            comparisonMessage = comparisonMessage,
            categoryProgress = categoryProgress
        )
    }.stateIn(
        scope = viewModelScope,
        started = SharingStarted.WhileSubscribed(5_000L),
        initialValue = BudgetUiState()
    )

    init {
        viewModelScope.launch {
            ensureCurrentMonthlyBudget()
        }
    }

    fun refreshCurrentPeriod() {
        currentDateFlow.value = System.currentTimeMillis()
    }

    fun createManualBudget(plannedAmount: Long) {
        if (plannedAmount <= 0L) {
            return
        }
        viewModelScope.launch {
            upsertManualBudget(plannedAmount)
        }
    }

    fun editCurrentBudget(plannedAmount: Long) {
        if (plannedAmount <= 0L) {
            return
        }
        viewModelScope.launch {
            upsertManualBudget(plannedAmount)
        }
    }

    private suspend fun ensureCurrentMonthlyBudget() {
        val now = System.currentTimeMillis()
        val budget = budgetRepository
            .getBudgetForDateStream(BudgetCycleType.MONTHLY, now)
            .first()
        if (budget != null) {
            return
        }

        val categories = categoryRepository.getAllCategoriesStream().first()
        val expenseCategories = categories.filter { it.type == TYPE_EXPENSE }

        val defaultWallet = getOrCreateDefaultWallet()
        val (periodStart, periodEnd) = getMonthRange(now)

        val budgetFromCategoryLimit = expenseCategories.sumOf { it.monthlyBudgetLimit ?: 0L }
        val plannedAmount = if (budgetFromCategoryLimit > 0L) {
            budgetFromCategoryLimit
        } else {
            DEFAULT_PLANNED_BUDGET
        }

        val newBudget = Budget(
            userId = defaultWallet.userId,
            walletId = defaultWallet.id,
            name = "Ngân sách tháng",
            cycleType = BudgetCycleType.MONTHLY,
            periodStart = periodStart,
            periodEnd = periodEnd,
            plannedAmount = plannedAmount,
            carryOverAmount = 0L,
            autoResetEnabled = true,
            carryOverEnabled = true,
            isAutoGenerated = true,
            manualOverride = false
        )
        budgetRepository.insertBudget(newBudget)

        if (expenseCategories.isNotEmpty()) {
                val allocations = buildBalancedAllocations(
                budgetId = newBudget.id,
                expenseCategories = expenseCategories,
                plannedAmount = plannedAmount
            )
            budgetRepository.upsertAllocations(newBudget.id, allocations)
        }
    }

    private suspend fun upsertManualBudget(plannedAmount: Long) {
        val now = System.currentTimeMillis()
        val existingBudget = budgetRepository
            .getBudgetForDateStream(BudgetCycleType.MONTHLY, now)
            .first()

        val categories = categoryRepository.getAllCategoriesStream().first()
        val expenseCategories = categories.filter { it.type == TYPE_EXPENSE }

        if (existingBudget == null) {
            val defaultWallet = getOrCreateDefaultWallet()
            val (periodStart, periodEnd) = getMonthRange(now)

            val manualBudget = Budget(
                userId = defaultWallet.userId,
                walletId = defaultWallet.id,
                name = "Ngân sách tháng",
                cycleType = BudgetCycleType.MONTHLY,
                periodStart = periodStart,
                periodEnd = periodEnd,
                plannedAmount = plannedAmount,
                carryOverAmount = 0L,
                autoResetEnabled = true,
                carryOverEnabled = true,
                isAutoGenerated = false,
                manualOverride = true
            )
            budgetRepository.insertBudget(manualBudget)

            if (expenseCategories.isNotEmpty()) {
                val allocations = buildBalancedAllocations(
                    budgetId = manualBudget.id,
                    expenseCategories = expenseCategories,
                    plannedAmount = plannedAmount
                )
                budgetRepository.upsertAllocations(manualBudget.id, allocations)
            }
            return
        }

        val updatedBudget = existingBudget.copy(
            plannedAmount = plannedAmount,
            isAutoGenerated = false,
            manualOverride = true
        )
        budgetRepository.updateBudget(updatedBudget)

        val currentAllocations = budgetRepository
            .getAllocationsByBudgetStream(existingBudget.id)
            .first()
        if (expenseCategories.isNotEmpty()) {
            val currentAllocationWeights = currentAllocations.associate { allocation ->
                allocation.categoryId to allocation.allocatedAmount
            }
            val allocations = buildBalancedAllocations(
                budgetId = existingBudget.id,
                expenseCategories = expenseCategories,
                plannedAmount = plannedAmount,
                weightByCategoryId = currentAllocationWeights
            )
            budgetRepository.upsertAllocations(existingBudget.id, allocations)
        }
    }

    private suspend fun getOrCreateDefaultWallet(): Wallet {
        val existingWallet = walletRepository.getWalletsStream().first().firstOrNull()
        if (existingWallet != null) {
            return existingWallet
        }

        val createdWallet = Wallet(
            userId = DEFAULT_LOCAL_USER,
            name = DEFAULT_WALLET_NAME,
            balance = 0L
        )
        walletRepository.insertWallet(createdWallet)
        return createdWallet
    }

    private fun buildBalancedAllocations(
        budgetId: String,
        expenseCategories: List<Category>,
        plannedAmount: Long,
        weightByCategoryId: Map<String, Long> = emptyMap()
    ): List<BudgetAllocation> {
        if (expenseCategories.isEmpty()) {
            return emptyList()
        }

        val safePlannedAmount = plannedAmount.coerceAtLeast(0L)
        val hasCustomWeights = weightByCategoryId.isNotEmpty()
        val rawWeights = expenseCategories.map { category ->
            val customWeight = weightByCategoryId[category.id]
            val defaultWeight = category.monthlyBudgetLimit
            when {
                hasCustomWeights -> customWeight ?: 0L
                else -> defaultWeight ?: 0L
            }.coerceAtLeast(0L)
        }
        val totalWeight = rawWeights.sum()

        val allocatedValues = if (totalWeight > 0L) {
            var distributed = 0L
            rawWeights.mapIndexed { index, weight ->
                if (index == rawWeights.lastIndex) {
                    (safePlannedAmount - distributed).coerceAtLeast(0L)
                } else {
                    val value = (safePlannedAmount.toDouble() * weight.toDouble() / totalWeight.toDouble())
                        .toLong()
                        .coerceAtLeast(0L)
                    distributed += value
                    value
                }
            }
        } else {
            val evenAmount = safePlannedAmount / expenseCategories.size
            expenseCategories.mapIndexed { index, _ ->
                if (index == expenseCategories.lastIndex) {
                    safePlannedAmount - (evenAmount * (expenseCategories.size - 1))
                } else {
                    evenAmount
                }
            }
        }

        return expenseCategories.mapIndexed { index, category ->
            BudgetAllocation(
                budgetId = budgetId,
                categoryId = category.id,
                allocatedAmount = allocatedValues[index]
            )
        }
    }

    private fun getPreviousMonthRange(currentPeriodStart: Long): Pair<Long, Long> {
        val previousMonthTimestamp = Calendar.getInstance().run {
            timeInMillis = currentPeriodStart
            add(Calendar.MONTH, -1)
            timeInMillis
        }
        return getMonthRange(previousMonthTimestamp)
    }

    private fun getMonthRange(timestamp: Long): Pair<Long, Long> {
        val calendar = Calendar.getInstance().apply {
            timeInMillis = timestamp
            set(Calendar.DAY_OF_MONTH, 1)
            set(Calendar.HOUR_OF_DAY, 0)
            set(Calendar.MINUTE, 0)
            set(Calendar.SECOND, 0)
            set(Calendar.MILLISECOND, 0)
        }

        val start = calendar.timeInMillis
        calendar.add(Calendar.MONTH, 1)
        calendar.add(Calendar.MILLISECOND, -1)
        val end = calendar.timeInMillis

        return start to end
    }

    private fun percentage(value: Long, total: Long): Int {
        if (total <= 0L) {
            return 0
        }
        return ((value * 100f) / total).toInt().coerceAtLeast(0)
    }

    private fun mapUsageToState(usagePercent: Int): BudgetProgressState {
        return when {
            usagePercent >= 100 -> BudgetProgressState.DANGER
            usagePercent >= 80 -> BudgetProgressState.WARNING
            else -> BudgetProgressState.SAFE
        }
    }

    private fun buildAlertMessage(usagePercent: Int): String? {
        return when {
            usagePercent >= 100 -> "Bạn đã vượt ngân sách kỳ này"
            usagePercent >= 80 -> "Bạn đã dùng hơn 80% ngân sách"
            else -> null
        }
    }

    private fun formatPeriodLabel(dateMillis: Long): String {
        return SimpleDateFormat("MM/yyyy", Locale("vi", "VN")).format(dateMillis)
    }

    private fun formatCurrency(value: Long): String {
        val formatter = NumberFormat.getCurrencyInstance(Locale("vi", "VN"))
        return formatter.format(value).replace("₫", "").trim() + " ₫"
    }
}
