package com.finflow.moneytracker.ui.budget

import android.content.res.ColorStateList
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.core.content.ContextCompat
import androidx.fragment.app.Fragment
import androidx.fragment.app.viewModels
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.lifecycleScope
import androidx.lifecycle.repeatOnLifecycle
import androidx.recyclerview.widget.LinearLayoutManager
import com.finflow.moneytracker.R
import com.finflow.moneytracker.databinding.FragmentBudgetBinding
import com.finflow.moneytracker.di.AppViewModelProvider
import com.google.android.material.dialog.MaterialAlertDialogBuilder
import com.google.android.material.textfield.TextInputEditText
import com.google.android.material.textfield.TextInputLayout
import java.text.NumberFormat
import java.util.Locale
import kotlinx.coroutines.launch

class BudgetFragment : Fragment() {

	private var _binding: FragmentBudgetBinding? = null
	private val binding get() = _binding!!

	private val viewModel: BudgetViewModel by viewModels {
		AppViewModelProvider.Factory
	}

	private lateinit var categoryAdapter: BudgetCategoryAdapter
	private var latestState: BudgetUiState = BudgetUiState()

	override fun onCreateView(
		inflater: LayoutInflater,
		container: ViewGroup?,
		savedInstanceState: Bundle?
	): View {
		_binding = FragmentBudgetBinding.inflate(inflater, container, false)
		return binding.root
	}

	override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
		super.onViewCreated(view, savedInstanceState)
		setupRecyclerView()
		setupActions()
		observeUiState()
	}

	override fun onResume() {
		super.onResume()
		viewModel.refreshCurrentPeriod()
	}

	private fun setupRecyclerView() {
		categoryAdapter = BudgetCategoryAdapter()
		binding.rvBudgetCategories.apply {
			layoutManager = LinearLayoutManager(requireContext())
			adapter = categoryAdapter
		}
	}

	private fun observeUiState() {
		viewLifecycleOwner.lifecycleScope.launch {
			viewLifecycleOwner.repeatOnLifecycle(Lifecycle.State.STARTED) {
				viewModel.uiState.collect { state ->
					latestState = state
					renderState(state)
				}
			}
		}
	}

	private fun setupActions() {
		binding.btnCreateManual.setOnClickListener {
			showBudgetInputDialog(
				title = "Tạo ngân sách thủ công",
				defaultAmount = latestState.plannedBudget
			) { amount ->
				viewModel.createManualBudget(amount)
			}
		}

		binding.btnEditBudget.setOnClickListener {
			showBudgetInputDialog(
				title = "Chỉnh sửa ngân sách",
				defaultAmount = latestState.plannedBudget
			) { amount ->
				viewModel.editCurrentBudget(amount)
			}
		}
	}

	private fun renderState(state: BudgetUiState) {
		binding.tvBudgetPeriod.text = "Kỳ ${state.periodLabel}"
		binding.tvBudgetName.text = state.budgetName.ifBlank { "Ngân sách" }
		binding.tvBudgetWallet.text = "Ví: ${state.walletName}"
		binding.tvBudgetMode.text = when {
			state.isManualOverride -> "Chế độ thủ công (ưu tiên)"
			state.isAutoGenerated -> "Chế độ tự động"
			else -> "Chế độ ngân sách"
		}
		binding.tvTotalBudget.text = formatCurrency(state.totalBudget)
		binding.tvSpent.text = formatCurrency(state.spent)
		binding.tvRemaining.text = formatCurrency(state.remaining)
		binding.tvUsagePercent.text = "${state.usagePercent}%"
		binding.btnCreateManual.visibility = if (state.canCreateManually) View.VISIBLE else View.GONE
		binding.btnEditBudget.visibility = if (state.canEditManually) View.VISIBLE else View.GONE

		binding.pbBudgetUsage.progress = state.usagePercent.coerceAtMost(100)
		binding.pbBudgetUsage.progressTintList = ColorStateList.valueOf(
			when (state.progressState) {
				BudgetProgressState.SAFE -> ContextCompat.getColor(requireContext(), R.color.status_income)
				BudgetProgressState.WARNING -> ContextCompat.getColor(requireContext(), R.color.status_warning)
				BudgetProgressState.DANGER -> ContextCompat.getColor(requireContext(), R.color.status_expense)
			}
		)

		if (state.alertMessage.isNullOrBlank()) {
			binding.tvBudgetAlert.visibility = View.GONE
		} else {
			binding.tvBudgetAlert.visibility = View.VISIBLE
			binding.tvBudgetAlert.text = state.alertMessage
		}

		if (state.comparisonMessage.isNullOrBlank()) {
			binding.tvComparison.visibility = View.GONE
		} else {
			binding.tvComparison.visibility = View.VISIBLE
			binding.tvComparison.text = state.comparisonMessage
		}

		binding.tvEmptyState.visibility = if (state.isEmpty) View.VISIBLE else View.GONE
		binding.groupContent.visibility = if (state.isEmpty) View.GONE else View.VISIBLE

		categoryAdapter.submitList(state.categoryProgress)
	}

	private fun showBudgetInputDialog(
		title: String,
		defaultAmount: Long,
		onConfirm: (Long) -> Unit
	) {
		val context = requireContext()
		val inputLayout = TextInputLayout(context)
		val input = TextInputEditText(context)

		inputLayout.hint = "Số tiền ngân sách"
		inputLayout.addView(input)
		input.inputType = android.text.InputType.TYPE_CLASS_NUMBER
		if (defaultAmount > 0L) {
			input.setText(defaultAmount.toString())
		}

		MaterialAlertDialogBuilder(context)
			.setTitle(title)
			.setMessage("Ngân sách thủ công sẽ được ưu tiên hơn tự động.")
			.setView(inputLayout)
			.setPositiveButton("Lưu") { _, _ ->
				val value = input.text?.toString()?.trim()?.toLongOrNull() ?: 0L
				if (value > 0L) {
					onConfirm(value)
				}
			}
			.setNegativeButton("Hủy", null)
			.show()
	}

	private fun formatCurrency(value: Long): String {
		val formatter = NumberFormat.getCurrencyInstance(Locale("vi", "VN"))
		return formatter.format(value).replace("₫", "").trim() + " ₫"
	}

	override fun onDestroyView() {
		super.onDestroyView()
		_binding = null
	}
}