package com.finflow.moneytracker.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.UUID

@Entity(tableName = "budgets")
data class Budget(
    @PrimaryKey
    val id: String = UUID.randomUUID().toString(),
    val userId: String = "",
    @ColumnInfo(name = "wallet_id")
    val walletId: String? = null,
    val name: String,
    @ColumnInfo(name = "budget_type")
    val budgetType: Int = BudgetType.PERSONAL,
    @ColumnInfo(name = "cycle_type")
    val cycleType: Int = BudgetCycleType.MONTHLY,
    @ColumnInfo(name = "period_start")
    val periodStart: Long,
    @ColumnInfo(name = "period_end")
    val periodEnd: Long,
    @ColumnInfo(name = "planned_amount")
    val plannedAmount: Long,
    @ColumnInfo(name = "carry_over_amount")
    val carryOverAmount: Long = 0L,
    @ColumnInfo(name = "auto_reset_enabled")
    val autoResetEnabled: Boolean = true,
    @ColumnInfo(name = "carry_over_enabled")
    val carryOverEnabled: Boolean = false,
    @ColumnInfo(name = "is_auto_generated")
    val isAutoGenerated: Boolean = true,
    @ColumnInfo(name = "manual_override")
    val manualOverride: Boolean = false,
    @ColumnInfo(name = "updated_at")
    val updatedAt: Long = System.currentTimeMillis(),
    @ColumnInfo(name = "is_deleted")
    val isDeleted: Boolean = false
)

object BudgetCycleType {
    const val WEEKLY = 0
    const val MONTHLY = 1
    const val YEARLY = 2
}

object BudgetType {
    const val PERSONAL = 0
    const val FAMILY = 1
    const val TRAVEL = 2
}
